name: NeteaseMusic
on:
  push:
  workflow_dispatch:
    branches:
      - master
  schedule: 
    - cron: "*/1 * * * *" # 半天更新一次

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: npm install
      - name: index.js
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_ID: 137338880
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          REPO: "netease-cloud-music-card"
          AUTHOR: "Ykuee"
